spring:
  ai:
#    mcp:
#      client:
#        request-timeout: 60000
#        stdio:
#          servers-configuration: classpath:/ai/mcp-servers-config.json
    #        sse:
    #          connections:
    #            server1:
    #              url: http://localhost:8080
    #记忆
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            platform: mariadb
    # deepseek
    deepseek:
      api-key: ${ai.deep-key}
      chat:
        options:
          model: deepseek-chat
          temperature: 1.3
    # 阿里
    dashscope:
      api-key: ${ai.ali-key}
      #      chat:
      #        options:
      #          temperature:
      audio:
        synthesis:
          options:
            model: TTS-Realtime
      embedding:
        options:
          model: text-embedding-v4