spring:
  datasource:
    url: jdbc:mysql://${mysql.url}:3306/ai?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    # redis 配置
    redis:
      # Redis 数据库索引（默认为0）
      database: 0
      # Redis 服务器地址
      host: ${redis.url}
      # Redis 服务器连接端口
      port: 6379
      # Redis 服务器连接密码（默认为空）
      password: ${redis.password}
      #      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto
      update-strategy: not_empty
  configuration:
#    使用配置文件中的日志设置，默认是打印在控制台
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl