server:
  # 端口
  port: 8080
  tomcat:
    connection-timeout: 300000 #300秒

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  config:
    import:
      - "classpath:config/sa-token.yml"
      - "classpath:config/ai.yml"
      - "classpath:config/data.yml"

logging:
  file:
    name: logs  # 日志文件名，全路径