name: Java CI with Maven

env:
  NAME_BACK: -替换1
  NAME: -替换2

# 触发条件：push 到 master 分支时触发
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # 只有当提交信息以 "yes" 开头时才运行
    if: startsWith(github.event.head_commit.message, 'yes')

    runs-on: ubuntu-latest

    steps:
      # Step 1: 拉取代码
      - uses: actions/checkout@v4

      - name: Replace placeholder with password in application-prod.yml
        run: |
          sed -i "s/-替换1/${{ secrets.PASSWORD }}/" src/main/resources/application-prod.yml
          sed -i "s/-替换2/${{ secrets.PASSWORD }}/" src/main/resources/application-prod.yml


      # Step 3: 安装 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Step 4: Maven 构建
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 5: 部署到远程服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: target/${{ env.NAME_BACK }}.jar
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: root
          TARGET: /var/lib/docker/volumes/${{ env.NAME }}/_data/${{ env.NAME }}.jar
          SCRIPT_AFTER: |
            docker restart ${{ env.NAME }}
